### ISSUE TITLE
Problem restoring 'en' locale

### ISSUE THREAD

**Issue by enekonieto** [recogito/annotorious-openseadragon#104]
Steps:
1. Create Annotorious with `locale: 'en'`. Buttons are in English (ok).
2. Destroy with `destroy()` and recreate with `locale: 'nl'`. Buttons are in Dutch (ok).
3. Destroy with `destroy()` and recreate with `locale: 'en'`. Buttons are in Dutch (bad!).

If I use `es` instead of `en`, buttons are in Spanish in steps 1 and 3 (ok).

Failing in version 2.5.16 (latest)

**Comment by enekonieto** [comment]
Same error happens if you start with `nl` and change to `en` (only steps 2 and 3). Step 1 was only to prove this is related to `en`.

**Comment by rsimon** [comment]
Interesting... thanks for reporting, I'll look into it!

**Comment by enekonieto** [comment]
Could it be a `recogito-client-core` issue?

I think the problem is in `recogito-client-core/src/i18n/index.jsx` line 48:

    i18n.extend(MESSAGES[lang]);

`MESSAGES['en']` does not exist.

**Comment by rsimon** [comment]
Yes, indeed - it was an issue in `recogito-client-core`. I fixed it there now. The fix will be included with the next Annotorious/AnnotoriousOSD releases.

**Comment by rsimon** [comment]
Fix now available in the main branch + will go live with the upcoming v2.6.0 release
