### ISSUE TITLE
How to use  Aannotorious with OpenSeadragon in Typescript

### ISSUE THREAD

**Issue by shyamkumaryadav** [recogito/annotorious-openseadragon#108]

**Comment by rsimon** [comment]
I'm afraid I'm not a TypeScript developer and can't help with this question. (I would be very interested in getting a tutorial from someone myself.)

Would you mind asking the question on the [Gitter chat](https://gitter.im/recogito/annotorious)? As far as I know, some people there have successfully used Annotorious with TypeScript. (But I don't know about the OpenSeadragon version...)
