### ISSUE TITLE
Annotation ID's

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#11]
When you create an annotation through the UI, the new annotation is assigned an id, this takes the form #GUID.

Is the # part of some standard that needs to be there? I'll have to strip this out in order to save the annotation to a database with a column type of GUID.

Looks like I can add annotation without the #, so it's just an issue through the UI created ones.

**Comment by rsimon** [comment]
The # needs to be there to make them valid (relative) URIs, according to the WebAnnotation standard. At least as far as I understand the spec. Other than that, IDs are used for programmatic update and delete through the API. When just adding annotations, you could leave ID blank as you say (somewhat unsafe, if you want to update/delete through the API later) - or just assign any ID of your choice.

The API will later also allow you to override the auto-generated ID. Thats‘ [already implemented in RecogitoJS](https://github.com/recogito/recogito-js/wiki/Developer-Documentation#createannotationannotation-overrideid), but not yet in Annotorious.

**Comment by rsimon** [comment]
Support for externally (e.g. server-) generated IDs is now implemented. Docs will become available with the next release.
