### ISSUE TITLE
Single-click zoom no longer works after clicking an annotation

### ISSUE THREAD

**Issue by gvillar-Batura** [recogito/annotorious-openseadragon#120]
Hi,

First of all, thanks for the awesome work !

I am having issues with the zoom behaviour with Annotorious OpenSeadragon on an Angular app. 

When I have the annotations loaded but haven't interacted with them yet, the zoom works perfectly. But as soon as I click on an annotation, the zoom stops working. 

You can see the same behaviour in the example of the getting [started page](https://recogito.github.io/annotorious/getting-started/osd-plugin/) and [here](https://realtime-demo.annotorious.com/) too.

Has anyone encountered something like this? Any way to fix or change this behaviour?

Regards.

**Comment by rsimon** [comment]
Hi,

hm, I can't seem to reproduce the issue. I just tried both sample pages (Getting Started, Realtime demo), on Chrome + Firefox, and zoom seems to be working correctly, also when an annotation is selected (and after deselecting again). There does seem to be a new issue with touch/pinch on Firefox. (I'll investigate.) What browser/OS are you using?

Cheers,
Rainer

**Comment by gvillar-Batura** [comment]
Hi, 

Thank you for the reply. 

I am using Chrome 98.0.4758.102, Firefox 97.0 and Safari 15.3 under Mac OS 12.2. All browsers with the same behaviour, using mouse and only using click to zoom in. Overlay buttons seems to work fine.

Cheers

**Comment by rsimon** [comment]
Ah, understood, thanks. Yes, I think single-click zoom never really worked in any of the versions. I'll check what's necessary to support that behavior in the future.

**Comment by gvillar-Batura** [comment]
Thanks for looking into this!
