### ISSUE TITLE
"Add a comment..." field in delete annotation confirmation popup

### ISSUE THREAD

**Issue by enekonieto** [recogito/annotorious-openseadragon#127]
How to reproduce:
1) Select an annotation
2) Click down arrow and select Delete
3) A confirmation popup appears with Cancel and Ok buttons and a textfield with "Add a comment..." placeholder.

What was expected:
There should be no textfield in the popup. A title with something like "Are you sure you want to delete the annotation" would be advisable.

**Comment by rsimon** [comment]
Hi,

I'm not sure I understand the request. When you click the down-arrow on a text comment box, you have the option to edit or delete. If you click delete, the comment is removed instantly. Do you mean you would like to see an extra confirmation dialog? (That's currently not implemented.)

In editable mode (=not read-only), there is always a reply field. I.e. if you delete the only existing comment, there will still be an input field to add a new comment. Is this what you are not expecting?

**Comment by enekonieto** [comment]
Sorry, my fault, I mixed up delete comment with delete annotation.
