### ISSUE TITLE
"Annotation deselect when selecting programmatically" fix in this plugin?

### ISSUE THREAD

**Issue by Neirokin** [recogito/annotorious-openseadragon#137]
I have the same problem (https://github.com/recogito/annotorious/issues/207) with this plugin. Have you added a fix here?

**Comment by rsimon** [comment]
Ok, weird. Although the consequence is the same, this issue is completely different internally. It looks like OpenSeadragon just stops firing events after programmatic selection (it's not even possible to navigate the image). I'll investigate.

**Comment by thanhhau097** [comment]
I still face this problem with the newest version on the `main` branch. After we call `anno.selectAnnotation(annotationId)`, we can only interact with OSD when we hover the mouse over/click on the annotation. Can you please have a look again?

**Comment by rsimon** [comment]
Yikes - looks like I had my testing set up incorrectly the last time. I _think_ this should work now (after the commit above). But will need to check back more thoroughly later. I'm re-opening the issue.

**Comment by thanhhau097** [comment]
Thanks so much for a very quick fix. I tested it with my case and now it works well.
