### ISSUE TITLE
"disableSelect" from constructor does not affect anno.disableSelect property

### ISSUE THREAD

**Issue by EmKarr** [recogito/annotorious-openseadragon#141]
Even though I set the "disableSelect" in the OSD-annotorious constructor, "anno.disableSelect" is "undefined" until I set it directly.

Best,
Michael

**Comment by rsimon** [comment]
Transferring, because this is about the OSD version.

**Comment by rsimon** [comment]
Duplicate of #135. Already fixed & will go live with the next release.
