### ISSUE TITLE
Issue in selecting default rectangle annotation

### ISSUE THREAD

**Issue by vivsamcom** [recogito/annotorious-openseadragon#156]
I am new to Openseadragon and Annotorious library, I want to implement annotation on the openseadragon images. 
When I tried to annotate using rectangle or polygon I get below error. 
GesturePointList.addContact() Implausible contacts value.
And I am not able to release the mousecontrol (rectangle seems to attach with mouse and I am not able to release it after selecting).I am using the annotorious@2.7.10 version.

Thanks in advance.

**Comment by rsimon** [comment]
Weird. Which version of OpenSeadragon are you using (you need version 3.0+). Can you try downgrading to Annotorious 2.7.9 and check if the problem persists?

**Comment by rsimon** [comment]
P.S.: the messages you are seeing are probably unrelated. They are warnings from OpenSeadragon, and should be gone with the recent releases (3.1 and 4.0).

**Comment by vivsamcom** [comment]
Thanks for your quick response.
I am getting same issue with Annotorious 2.7.9.
I am using openseadragon 2.4.2.

Basically I am not able to release mouse pointer to complete the annotation on the image, If I click somewhere outside the image then it will allow.

**Comment by vivsamcom** [comment]
Thanks @rsimon , it worked with Annotorious version 2.6.0. 
Rectangle and Polygon are working in my app.

I have another issue regarding annotorious-selector-pack plugin
When I included the plugin I want to show the icons on toolbar like circle,ellipse,freehand.
I included the plugin however it dint show the tools so do I have to do any other steps.

my code 
 Annotorious.SelectorPack(anno, {
    tools: ['ellipse', 'freehand']
  });

**Comment by rsimon** [comment]
Make sure you include the Selector Pack plugin __before__ you include the Toolbar plugin. Otherwise the toolbar won't pick up the added tools.

**Comment by vivsamcom** [comment]
Perfect It worked.

**Comment by vivsamcom** [comment]
Is "line" tool available in the Selector Pack plugin?

**Comment by rsimon** [comment]
The line tool isn't quite finished yet. The last official release does not include the line tool yet. You could use the beta version if you build the selector pack from source. (Check out the repository, run `npm install` and `npm run build` in the project directory. Requires recent versions of node and npm installed on your machine.)

**Comment by vivsamcom** [comment]
Hi @rsimon,

I am now using the latest versions as mentioned below
openseadragon version - 4.0.0 , I have tried with version 3.1.0 as well
annotorious - 2.7.10

Issue: When I am drawing annotation I get comment box however when I click on Ok or Cancel button in comments popup nothing happens. Basically the events are not getting triggered. What could be the issue here?

Thanks,
Vivek

**Comment by vivsamcom** [comment]
Hi @rsimon ,

I have build the selector pack from source as you have mentioned and added line in the initialization using below 

Annotorious.SelectorPack(anno, {
        tools: ['ellipse', 'freehand', 'point', 'circle','line']
      });

However I am not able to get the line icon in toolbar. Do I have to perform any other steps ?

Thanks,
Vivek

**Comment by vivsamcom** [comment]
> Hi @rsimon ,
> 
> I have build the selector pack from source as you have mentioned and added line in the initialization using below
> 
> Annotorious.SelectorPack(anno, { tools: ['ellipse', 'freehand', 'point', 'circle','line'] });
> 
> However I am not able to get the line icon in toolbar. Do I have to perform any other steps ?
> 
> Thanks, Vivek

I have rebuild the toolbar plugin from source as well and it shows the line icon in toolbar now.

**Comment by vivsamcom** [comment]
I have rebuild the toolbar plugin from source as well and it shows the line icon in toolbar now.
