### ISSUE TITLE
Display SVG text?

### ISSUE THREAD

**Issue by Pixcell** [recogito/annotorious-openseadragon#162]
Hello,

I'm using annotorious to display polygons on an OpenSeaDragon image.
I'd like to display text directly on the image, in the same fashion than we display polygons.

I tried to create an annotation of type `SvgSelector` with a value of 
```
<svg><text x="50" y="50">Hello</text></svg>
```

Nothing apart from a small white square in the top left is being displayed. The console shows an error
```
Uncaught Unsupported SVG shape type: text
TE @ AnnotationStore.js:103
(anonymous) @ AnnotationStore.js:142
(anonymous) @ AnnotationStore.js:134
(anonymous) @ OSDAnnotationLayer.js:135
(anonymous) @ OSDAnnotationLayer.js:266
```

Versions:

    "@recogito/annotorious-openseadragon": "^2.7.10"
    "openseadragon": "^4.0.0"

Thank you!

**Comment by rsimon** [comment]
Sorry, Annotorious doesn't support text overlays. If you need a solution to overlay generic SVG, this might be what you are looking for: https://github.com/openseadragon/svg-overlay
