### ISSUE TITLE
readonly mode 

### ISSUE THREAD

**Issue by rsimon** [recogito/annotorious-openseadragon#2]
Just like in standard Annotorious. Should by mostly a bit of extra plumbing.

**Comment by bennlich** [comment]
This doesn't seem to work for me. After:

```
var anno = OpenSeadragon.Annotorious(viewer, {
    readOnly: true
})
```

if I click an annotation, I can still edit its size.

**Comment by rsimon** [comment]
Yikes. Good point. Readonly mode was introduced before shape editing, so this fell off the radar. Will look into it. Thanks for reporting!

**Comment by rsimon** [comment]
This is fixed now in the main branch. I hope to have a new release up in a couple of days (to support touch devices). This next release will then include the fix.
