### ISSUE TITLE
clear all annotations (≠ anno.destroy() )

### ISSUE THREAD

**Issue by atomotic** [recogito/annotorious-openseadragon#20]
i'm playing with [webview](https://github.com/webview/webview) to make a desktop app with annotorius that persists annotations locally into an sqlite file.

i will publish in github soon, meanwhile 👇
<img width="1000" alt="Screenshot 2020-06-29 at 17 40 32" src="https://user-images.githubusercontent.com/67420/86026260-b9f75200-ba1e-11ea-800f-90aec14de628.png">

the problem: i'm opening new canvases from IIIF manifest with [viewer.open()](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#open), but when changing the tile the annotation layer persists. i'm wondering if can be useful an api method to clear all annotations (not actually the current `destroy()` method)

this new `clear()` method could be sticked inside osd [open](https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:open) event.

or maybe i can use `anno.getAnnotations()` and then looping and remove every annotation?

PS/ right now .getAnnotations() seems missing
```o.annotationLayer.getAnnotations is not a function. (In 'o.annotationLayer.getAnnotations()', 'o.annotationLayer.getAnnotations' is undefined)```

**Comment by rsimon** [comment]
Good point. Maybe a `clearAnnotations` method would be nice. 

As far as functionality is concerned: you should get the same effect by setting `setAnnotations([])`. The empty array should replace the existing annotations if I remember correctly. But I'll double check...

**Comment by rsimon** [comment]
Also thanks, I'll check about `getAnnotations`.

**Comment by rsimon** [comment]
Yikes. I'm realizing that API-wise, the OpenSeadragon plugin lags further behind the standard version as I thought.

- `getAnnotations` was indeed broken. I just fixed this in the master branch.
- `setAnnotations` did __not__ remove existing annotations. I fixed this, too. You can now use `setAnnotations` to clear the annotation layer, and it's also ok to call it without argument. I.e. both this works:

```js
anno.setAnnotations([]);

anno.setAnnotations();
```

**Comment by rsimon** [comment]
P.S. I think in terms of API semantics, calling `setAnnotations` with empty or no argument feels sufficient, and there's maybe no need for an extra `clearAnnotations` method. But I'm happy to hear dissenting opinions :-)

**Comment by rsimon** [comment]
P.P.S: that webview client looks awesome! Looking forward to trying this out myself once you've published it.

**Comment by atomotic** [comment]
fixing `getAnnotations()` has solved the problem, i've not looked deeply the code but i don't need to `setAnnotations[]` empty

a quick demo: https://docuver.se/tmp/annotorius.app.mp4
(i'll fix some things on building and packaging and i will publish)

**Comment by rsimon** [comment]
Fantastic! Both using `getAnnotations` and then looping through the annotations using `removeAnnotation`. Although, technically, a call to `setAnnotations()` will be marginally faster, if you are being super-picky about it ;-)

**Comment by atomotic** [comment]
sorry, i explain better: after your fix of yesterday i don't need anymore to remove the previous annotations on canvas change.
https://github.com/atomotic/annotorius-desktop/blob/master/public/index.html#L34-L43

i published here https://github.com/atomotic/annotorius-desktop
is very very raw and incomplete, i spent on this just a couple of hours

**Comment by rsimon** [comment]
Ah - of course! Because `setAnnotations` now properly resets as it should. Thanks for the link! I'll try to install & test drive myself tonight :-)
