### ISSUE TITLE
Bug after polygon drawing

### ISSUE THREAD

**Issue by ufuk23** [recogito/annotorious-openseadragon#24]
There is a bug after the polygon drawing while clicking the cancel button on the editor panel. I draw a polygon then the editor panel appears and when I click the cancel button the editor panel disappears but the polygon does not. The polygon still appears even if clicking the cancel button. The same steps work while drawing a rectangle, but it doesn't work by drawing a polygon.

Could you fix this bug, please?

(tested with chrome browser)

**Comment by rsimon** [comment]
Fixed in the latest release.
