### ISSUE TITLE
Openseadragon editor popup location

### ISSUE THREAD

**Issue by ufuk23** [recogito/annotorious-openseadragon#28]
Hi,
While adding a new polygon, the editor popup shows out of the div, and sometimes we cannot see the popup because of that. 
While adding a new rectangle, the editor popup shows inside of the div, so there is no problem for the rectangle.

Can you fix this problem for the polygon?

![osd1](https://user-images.githubusercontent.com/8513827/98791860-b3d6a080-2416-11eb-8cc0-0c7f15d5a4ca.png)

**Comment by rsimon** [comment]
Thanks for reporting! This is a bug that sneaked in when the dim mask feature was introduced. It's fixed in the Annotorious master now, and will become available with the next release.

I see you added a new language! (Turkish?) Would you mind sharing it with the community through a pull request?

**Comment by ufuk23** [comment]
Thank you, you are so fast. Please let me know which files affected by this fix.
I will send the tr language file.

**Comment by rsimon** [comment]
Great, thanks. The affected files are all imported from the the [main Annotorious project](https://github.com/recogito/annotorious). They are:

- [src/tools/polygon/PolygonMask.js](https://github.com/recogito/annotorious/blob/master/src/tools/polygon/PolygonMask.js)
- [src/tools/polygon/RubberbandPolygon.js](https://github.com/recogito/annotorious/blob/master/src/tools/polygon/RubberbandPolygon.js)
- [src/tools/polygon/RubberbandPolygonTool.js](https://github.com/recogito/annotorious/blob/master/src/tools/polygon/RubberbandPolygonTool.js)

See this commit for full details on the changes:
https://github.com/recogito/annotorious/commit/2e473a4e1a1b7a1e237843b4e26513d56e7b7500

**Comment by ufuk23** [comment]
Thank you so much, now it works perfectly. I am new to Github, so I am not sure how I can add the lang file to the project. I think I should have the push permission, right? If I cannot do it, here is the file content:

messages_tr.json (must be in the i18n folder)

{
  "Add a comment...": "Yorum ekle...",
  "Add a reply...": "Cevap ekle...",
  "Add tag...": "Tag Ekle...",
  "Cancel": "İptal",
  "Close": "Kapat",
  "Edit": "Düzenle",
  "Delete": "Sil",
  "Ok": "Tamam"
}

**Comment by rsimon** [comment]
If you want to add the file, you need to fork the recogito-client-core repository to your own GitHub account, commit the file there, and create a pull request. (This is possible via the GitHub website.) But don't worry, I can add the file if you want. Many thanks for translating and sharing!

**Comment by ufuk23** [comment]
You're welcome. I think I created a pull request for that file as you want. Thanks for the explanation.

**Comment by rsimon** [comment]
Yes, worked perfectly & is already merged with the master branch.
