### ISSUE TITLE
Formatter not called

### ISSUE THREAD

**Issue by ddankwerth** [recogito/annotorious-openseadragon#30]
I switched from using "plain" plugin to the openseadragon plugin and it seems like the formatter callback is not called, in the plain plugin i used this callback to add a class to thr annotation g element
Is it a bug ? 
Thanks

**Comment by rsimon** [comment]
No, I only added the formatter to the OSD implementation recently. It's available in the current master branch, but not yet in the latest release. Will go live with the next release though.

**Comment by rsimon** [comment]
Next release coming tomorrow.
