### ISSUE TITLE
Disable Annotorious Plugin (Editor + Draw)

### ISSUE THREAD

**Issue by quinlo** [recogito/annotorious-openseadragon#48]
I see headless mode (and disableEditor) allows for just the drawing aspect of the plugin... is there a way to disable the draw and the editor programatically?  End goal here is to allow users to toggle annotorious on and off as needed.

**Comment by rsimon** [comment]
Depends on which combination of functionalities you want to disable exactly. `setVisible` might be what you want? That hides the annotation layer. 

Or `readOnly`? That disables drawing and shape modification, but users can still select and view annotations.

**Comment by quinlo** [comment]
Sounds like both setVisible and readOnly will do the trick to hide the annotations _and_ disable the draw tool.  I will stay tuned for the setVisible fix in the next release candidate!  Thanks for the quick reply.   Great work on this tool.

**Comment by quinlo** [comment]
I saw the commit to fix setVisible.  Any estimate when this will make it to another release version?
