### ISSUE TITLE
Getting error for .addAnnotation()

### ISSUE THREAD

**Issue by johnguirgis** [recogito/annotorious-openseadragon#53]
I am having trouble loading annotations after they are created. I can create the annotations fine but once I refresh the page, they are gone. I think it has something to do with this error I am getting 
<img width="765" alt="Screen Shot 2021-05-28 at 3 13 20 PM" src="https://user-images.githubusercontent.com/62853290/120031798-44e22300-bfc7-11eb-8299-5c027d9a453b.png">
<img width="668" alt="Screen Shot 2021-05-28 at 3 12 56 PM" src="https://user-images.githubusercontent.com/62853290/120031802-46abe680-bfc7-11eb-9b18-27d845caefae.png">

**Comment by rsimon** [comment]
Sorry I don't quite understand the problem. Do you mean you are re-loading annotations you have created before? Can you post your code and an example annotation that causes the problem?

**Comment by johnguirgis** [comment]
Thanks for your response.
Here is the relevant portion of code
<img width="446" alt="Screen Shot 2021-05-28 at 4 08 08 PM" src="https://user-images.githubusercontent.com/62853290/120036992-ed47b580-bfce-11eb-8eac-5cb139232b40.png">
I am pretty certain that the annotation object is fine since the `convert_annotation_w3c` function is used elsewhere and works fine, but for some reason the call to `.addAnnotation()` is giving an error.
My issue is that after I create an annotation and refresh the page, the annotation is gone, I need it so that the annotations are saved and show up whenever the page is loaded.

**Comment by rsimon** [comment]
Can you post an example annotation object?

**Comment by rsimon** [comment]
FWIW: I just tested in Annotorious + Annotorious OpenSeadragon and `.addAnnotation()` seems to work properly. I.e. pretty sure that the annotation your are passing is invalid in some way. If `convert_annotation_w3c` works elsewhere, it might have something to do with the data you are receiving from the AJAX request.

**Comment by johnguirgis** [comment]
Here's an example annotation object: 
<img width="507" alt="Screen Shot 2021-05-29 at 10 28 20 AM" src="https://user-images.githubusercontent.com/62853290/120074062-1157d500-c069-11eb-8a80-24cc77588754.png">

**Comment by rsimon** [comment]
Sorry that's not really readable. It doesn't print out the whole annotation. Can you simply `JSON.stringify(...)`, so that we can see the actual JS object?

Is this the actual object you are handing to .addAnnotation? I.e. is this what you got when you logged `w3c`?

As I said, I cannot reproduce your issue with valid annotations. Therefore, unless we can get enough info on where your annotations differ, I won't be able to help you.

**Comment by johnguirgis** [comment]
Sorry about that, is this better?
<img width="507" alt="Screen Shot 2021-05-29 at 11 14 02 AM" src="https://user-images.githubusercontent.com/62853290/120075388-0d2eb600-c06f-11eb-8728-2dc4851319e4.png">

**Comment by rsimon** [comment]
Yes. That's a text annotation, not an image annotation. Therefore, this cannot work on Annotorious. I assume you're getting this out of RecogitoJS?

**Comment by johnguirgis** [comment]
Turns out there was another issue with the text annotations on the same page that was causing all these problems, but I have resolved it now so everything is working fine.
Thanks for your help @rsimon !!
