### ISSUE TITLE
getAnnotations method throws an error when called from selectAnnotation event handler

### ISSUE THREAD

**Issue by umesh-timalsina** [recogito/annotorious-openseadragon#54]
While trying to get all the current annotations in the `selectAnnotation` event handler, the following error is thrown:

```js
OpenSeadragonAnnotator.jsx:241 Uncaught (in promise) TypeError: Cannot read property 'clone' of undefined
    at OpenSeadragonAnnotator.jsx:241
    at Array.map (<anonymous>)
    at p.getAnnotations (OpenSeadragonAnnotator.jsx:241)
    at e.getAnnotations (index.js:131)
    at (index):101
    at n.emit (index.js:36)
    at Object.onAnnotationSelected (index.js:73)
    at p.<anonymous> (OpenSeadragonAnnotator.jsx:83)
    at index.js:271
    at Array.some (<anonymous>)
```

**Comment by rsimon** [comment]
Hi, that's actually a duplicate to this issue in Annotorious (standard version):

https://github.com/recogito/annotorious/issues/120

.getAnnotations() throws this error when an annotation is currently selected.

The good news is: it's already fixed. But only in the latest state of the main branch. The bug still exists in the latest release, but will be gone with the next.

**Comment by umesh-timalsina** [comment]
@rsimon. Thanks. I am closing this issue since its resolved in https://github.com/recogito/annotorious/issues/120.
