### ISSUE TITLE
destroy()

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#6]
There does not appear to be a .destroy() method. Subsequent .init() methods seem to work though, so switch between different images with .init() works, but previous versions have had .destroy() method.

**Comment by rsimon** [comment]
Please refer to the [API](https://github.com/recogito/annotorious-openseadragon/wiki/API-Reference) for the list of currently implemented methods. As documented, there is currently no `destroy()`. Don’t worry, it‘s all on the list. Just a little patience please - or pull requests :-)
