### ISSUE TITLE
Make mouseEnterAnnotation and mouseLeaveAnnotation public.

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#7]
Can the events mouseEnterAnnotation(annotation, e) and mouseLeaveAnnotation(annotation, e) be make public.

**Comment by rsimon** [comment]
Yes, this is also on the list.

**Comment by ZENUAV** [comment]
Send me message when min.js is updated! Great work, the other mods work great!

**Comment by rsimon** [comment]
Hi, I just updated the build on the demo page.

**Comment by ZENUAV** [comment]
Brilliant! Thank you, will check out new functionality!

Jason

Sent from my iPhone

On 17 May 2020, at 19:07, Rainer Simon <notifications@github.com> wrote:

﻿

Hi, I just updated the build on the demo page.

**Comment by ZENUAV** [comment]
Hi Rainer

Not sure if I’m doing this wrong, but I can’t get any of the following to work?

selectAnnotation, panTo, fitbounds or mouseEnter/Leve events??

Example :

anno.on('mouseEnterAnnotation', function (annotation, e) {
                console.log('mouseEnterAnnotation', annotation);
            });

**Comment by rsimon** [comment]
Weird - either the GitHub page didn't update properly, or I managed to deploy the wrong thing yesterday night. I redeployed & things should work now.

**Comment by ZENUAV** [comment]
It happens!! Thanks, I’ll have a play today!
