### ISSUE TITLE
createSelection throws error on headless mode with openseadragon

### ISSUE THREAD

**Issue by alaksandarjesus** [recogito/annotorious-openseadragon#70]
i am trying to integrate angular, openseadragon and annotorius
 "@angular/core": "~11.2.11",
    "@recogito/annotorious-openseadragon": "^2.4.2",
    "@types/openseadragon": "^2.4.7",

My code implementation can be followed at (unfortunately both did not work, but works in my local project)

https://codesandbox.io/s/quizzical-shape-g0y3d

https://stackblitz.com/edit/angular-ivy-c4ogjd

I was able to draw the annotation. After drawing the annotation, if the annotation is selected, it throws an error. 

![image](https://user-images.githubusercontent.com/4712552/125978201-55c34788-a217-4808-9d88-c99b8ae6bd33.png)

I have followed CODE EXAMPLE section of https://recogito.github.io/guides/headless-mode/

**Comment by rsimon** [comment]
I created a ticket now for the larger issue that this is related to:
https://github.com/recogito/annotorious-openseadragon/issues/74

I'll try to prioritize this!

**Comment by rsimon** [comment]
Headless mode is now revised & fixed. It's now possible to create an annotation properly.

- After an annotation is created in headless mode, it remains in selected state
- You can store annotation bodies & save the annotation through the API (see [updateSelected](https://recogito.github.io/annotorious/api-docs/osd-plugin/#updateselected) and [saveSelected](https://recogito.github.io/annotorious/api-docs/osd-plugin/#saveselected))
- Clicking outside the annotation will also save it. Note that annotations without bodies will be canceled, unless the `allowEmpty` init parameter is set to `true`
