### ISSUE TITLE
cancelSelected fired when selecting other annotation programmatically

### ISSUE THREAD

**Issue by enekonieto** [recogito/annotorious-openseadragon#77]
If you select an annotation using `selectAnnotation()`, `selectAnnotation` event won't be launched (nice!), but if another annotation was previously selected it will launch `cancelSelected` event (not nice).

Is this intended? Is there a way to detect such situations (that selection was cancelled because another annotation was selected)?

Thanks!

**Comment by rsimon** [comment]
Yes that's the intended behavior. Deselect (without save/update) corresponds to a cancel event. There's currently no way to distinguish a "deselect-cancel" from an explicitly triggered cancel.
