### ISSUE TITLE
Headless mode for AnnotoriousOSD

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#8]
Can we prevent the default Editor/CommentWidget from showing.

Something like

`var anno = AnnotoriousOSD.init(openSeadragonViewer, { showEditor: true/false } );`

Then using the selectAnnotation and createAnnotation events a dev can popup there own Editor.

**Comment by rsimon** [comment]
Yep, also on the list.

FWIW, this feature exists for the ['normal' non-Seadragon Annotorious](https://github.com/recogito/annotorious) and will be implemented here as well, when I get the time. It’s called headless mode over there. However if you want to __change__ the editor, rather then remove it altogether, I‘d recommend a different approach. The editor is pretty flexible: you can add or exchange the widgets inside, while much of the plumbing is still handled for you. Therefore, it might be easier to fork the project and modify the index.js file - which defines the editor widgets. (Plus provide your own CSS for full freedom.)

I‘m going to write a tutorial about this later to make it easier. But might take while. (This is currently a weekend project for me.)

**Comment by ZENUAV** [comment]
Many thanks for this tool. I'm very happy to test it as you progress with it's development. Headless mode is definitely the way forward for me. I'm not 100% sure a pull request is the way forward for me, never done it before!

**Comment by rsimon** [comment]
Headless mode is now available in the [latest version (2.2.0)](https://github.com/recogito/annotorious-openseadragon/releases/tag/v2.2.0).
