### ISSUE TITLE
Calling anno.getSelected() after anno.cancelSelected() returns a selection

### ISSUE THREAD

**Issue by enekonieto** [recogito/annotorious-openseadragon#83]
1)  Select an annotation with `anno.selectAnnotation()`
2) Cancel it with `anno.cancelSelected()`
3) Calling `anno.getSelected()` returns the previous selection, undefined or null was expected.

Same behaviour in 2.5.2 and 2.5.5.

**Comment by rsimon** [comment]
Yikes - this is actually a combination of a bug and a design feature... Thanks for reporting! 

I'll fix the bug with the next release. After the fix, this will work:

```js
// 1. select annotation 
anno.selectAnnotation('...');

// 2. Cancel & wait for async operation to complete
await anno.cancelSelected();

// 3. Prints undefined
console.log(anno.getSelected());
``` 

Note that `cancelSelected` is an async operation. Therefore, you need to use `await` __if you want to use getSelected immediately after cancelSelected__.
