### ISSUE TITLE
OSD launches "delegate is undefined" after recreating Annotorious

### ISSUE THREAD

**Issue by enekonieto** [recogito/annotorious-openseadragon#85]
Steps to reproduce:
1) Create Annotorious above OSD
```
const viewer: OpenSeadragon({
        element: this.viewer.nativeElement,
        showNavigator: true,
        navigatorPosition: 'BOTTOM_RIGHT',
        maxZoomPixelRatio: 1.5,
        zoomPerClick: 1.5,
        zoomPerScroll: 1.5,
        showNavigationControl: false,
        gestureSettingsMouse: {
          scrollToZoom: false,
          flickEnabled: true
        }
});
const anno = Annotorious(viewer, config);
```

2) Recreate Annotorious (In my use case user clicks another image)
```
viewer.open({
        type: 'image',
        url: photo.uri
      });
if (anno !== undefined) {
      anno.destroy();
}
anno = Annotorious(viewer, config);
```

3) Pressing Shift (trying to create a new annotation) causes OSD to launch "delegate is undefined" error.

If instead of using `destroy()` I use `clearAnnotations()` and remove listener with` off()` the error does not happen.

Thanks in advance, nice work!

**Comment by rsimon** [comment]
Thanks for reporting! Fix will be available with the next release (hopefully soon).
