### ISSUE TITLE
Update problem while editing shapes

### ISSUE THREAD

**Issue by ufuk23** [recogito/annotorious-openseadragon#86]
I use the annotorious with annotorious-shape-labels.min.js like below. When I edit the shape, it is not updated with the last values. I get x, y, width, height values of the shape always as first values, so the shape values (x, y, width, height) cannot be changed for the second time.

```
        anno = Annotorious.init({
          image: 'hallstatt',
          locale: 'auto',
	  disableEditor: true,
	  formatter: Annotorious.ShapeLabelsFormatter()
        });
```

The picture below shows that the rectangle x,y, width, height are not correct values after editing the shape.
![image](https://user-images.githubusercontent.com/8513827/125261904-5fb7ef00-e30a-11eb-9b56-521b4fefa61e.png)

**Comment by rsimon** [comment]
Click outside is now implemented (#76). The only other option (by design) to "save" an annotation is by using the API. E.g. an application using headless mode could have a save button underneath the image that calls the API `.saveSelected` method.
