### ISSUE TITLE
Formatters for AnnotoriousOSD

### ISSUE THREAD

**Issue by ZENUAV** [recogito/annotorious-openseadragon#9]
How can we add annotation with style options such as line colour, width etc.

Looked at Web Annotation Model and came up with this

            var annotation = [
                {
                    "type": "Annotation",
                    "stylesheet": {
                        "type": "CssStylesheet",
                        "value": ".red { color: red }"
                    },
                    "body": [{ "type": "TextualBody", "value": "Logo", "purpose": "commenting" }],
                    "target": { "selector": { "type": "FragmentSelector", "conformsTo": "http://www.w3.org/TR/media-frags/", "value": "xywh=pixel:4529.12646484375,1530.34130859375,871.17236328125,131.33251953125" }, "styleClass": "red" },
                    "@context": "http://www.w3.org/ns/anno.jsonld", "id": "#3e4502d0-923a-11ea-95ff-25ef2ceeaad8"
                }]

but it did not display annotation in a red colour.

**Comment by rsimon** [comment]
I‘m not yet making use of style info in the annotation. But the annotations are rendered as SVG shapes (inside a `g` with CSS class `a9s-annotation`). This way you can already override styles in your own stylesheet. 

Likewise, I‘m planning to write a guide for this on the  [Annotorious Wiki](https://github.com/recogito/annotorious/wiki)... when there‘s time ;-)

**Comment by ZENUAV** [comment]
I'm after more flexibility than that.

**Use Case**

- User draws annotation
- Custom editor allows user to add comment and specify severity ~ green, orange, red type of system
- Annotation is saved and displayed in the severity colour

**Comment by rsimon** [comment]
Yes, also coming :-) [RecogitoJS](https://github.com/recogito/recogito-js), the text annotation companion project has a concept called formatters, where you can configure a function to emit a specific CSS class based on the annotation. I.e. you can supply a function that looks into some kind of severity tag body and then the annotation would get e.g. `green`, `orange` etc. as an extra CSS class & you can attach styles. First, you‘d probably want an extra 'severity widget' in the editor though.

I built something similar for a client for RecogitoJS very recently. We can also talk off-list if you want or have specific integration needs at short time frame.

**Comment by ZENUAV** [comment]
Here's an example setting the style through css as you suggested. It's a JQuery example, but might go into your Wiki guide.

```
// get annotation element of type g with data-id of @context.id
var element = $('g[data-id="#3e4502d0-923a-11ea-95ff-25ef2ceeaad8"]');

// get outer rect and set style
var outerRect = element.children('rect').first();
outerRect.css({ stroke: 'red', 'stroke-width': '5px', 'stroke-dasharray': '5' });

// get inner rect and set style
var innerRect = element.children('rect').first().next();
innerRect.css({ stroke: 'white', 'stroke-width': '2px' });
```

The styles would be applied post render, which works on my test as it only draw a few annotations, for 100's it might be possible to add annotations that are hidden, apply styles, then make them visible?

**Comment by ZENUAV** [comment]
Regarding custom mods, I'm a single developer start-up with no cash! I'll have just work with it as it develops. Beggars can't be choosers, as they say!

**Comment by rsimon** [comment]
Yes, that’s a good workaround before I can implement formatters.

No worries, I know the situation ;-)
