### ISSUE TITLE
Openseadragon toolbar - fade out problem

### ISSUE THREAD

**Issue by ufuk23** [recogito/annotorious-openseadragon#90]
The toolbar of openseadragon that has zoom in, zoom out etc. buttons is fading out and not fading in even by mouse over movenement. Is there any wat to fix it?
Regards.

**Comment by rsimon** [comment]
Does this happen only when using the Annotorious plugin? I can't reproduce it on the [demo page](https://recogito.github.io/annotorious/getting-started/osd-plugin/), so this might be specific to your application or web page (e.g. surrounding markup or app-specific CSS).

Please note that Annotorious is not directly affiliated with OpenSeadragon. For general OpenSeadragon issues, please contact the [OSD developer chat](https://gitter.im/openseadragon/openseadragon) or the [OpenSeadragon Github](https://github.com/openseadragon/openseadragon) issue tracker.
