### ISSUE TITLE
headless mode events: updateSelected -> createAnnotation

### ISSUE THREAD

**Issue by atomotic** [recogito/annotorious-openseadragon#91]
https://recogito.github.io/guides/headless-mode/
_After you have called updateSelected, the annotation is still in draft state. To make the change persistent, you need to save it by calling saveSelected. This will persist the change (and Annotorious will fire createAnnotation or updateAnnotation events accordingly)._

after calling `anno.updateSelected(selection, true);` the **createAnnotation** event is not automatically fired, until click on the image, out of the newly created annotation

**Comment by rsimon** [comment]
Weird... thanks for reporting - will look into it!

**Comment by rsimon** [comment]
Looks like there were actually multiple issues. `getSelected` was also broken for headless mode, since the last release. Yikes. Should be all fixed now if you build from source. Otherwise, the next release will probably come fairly soon.
