### ISSUE TITLE
bug in fragementUnit: "percentage" 

### ISSUE THREAD

**Issue by dnoneill** [recogito/annotorious-openseadragon#93]
When you try to load percentage annotations into the viewer I get a large bug. See below.

TypeError: undefined is not an object (evaluating 't.naturalWidth')

**Comment by rsimon** [comment]
Thanks for reporting! Yikes... that's a nasty one - and definitely an oversight on my part. Looks like annotation loading happens before the image is actually loaded in the OSD viewer, which means the image width/height (necessary to sort/draw) the annotations isn't known yet.

This is likely to remain broken for a while, until I find the time to sort out the load sequence.
